#pragma once
#include <vector>
#include <string>


const std::vector<std::string> psfs = {
    "(Str) type == 'WatchEvent'",
    "(Str) type == 'ReleaseEvent'",
    "(Str) type == 'PushEvent'",
    "(Str) type == 'PullRequestReviewEvent'",
    "(Str) type == 'PullRequestReviewCommentEvent'",
    "(Str) type == 'PullRequestEvent'",
    "(Str) type == 'PublicEvent'",
    "(Str) type == 'MemberEvent'",
    "(Str) type == 'IssuesEvent'",
    "(Str) type == 'IssueCommentEvent'",
    "(Str) type == 'GollumEvent'",
    "(Str) type == 'ForkEvent'",
    "(Str) type == 'DeleteEvent'",
    "(Str) type == 'CreateEvent'",
    "(Str) type == 'CommitCommentEvent'",
    "(Str) payload.pull_request.head.repo.language == 'Markdown'",
    "(Str) payload.pull_request.head.repo.language == 'Mustache'",
    "(Str) payload.pull_request.head.repo.language == 'TeX'",
    "(Str) payload.pull_request.head.repo.language == 'Assembly'",
    "(Str) payload.pull_request.head.repo.language == 'Elixir'",
    "(Str) payload.pull_request.head.repo.language == 'R'",
    "(Str) payload.pull_request.head.repo.language == 'Swift'",
    "(Str) payload.pull_request.head.repo.language == 'MDX'",
    "(Str) payload.pull_request.head.repo.language == 'Jinja'",
    "(Str) payload.pull_request.head.repo.language == 'Smarty'",
    "(Str) payload.pull_request.head.repo.language == 'Julia'",
    "(Str) payload.pull_request.head.repo.language == 'Lua'",
    "(Str) payload.pull_request.head.repo.language == 'Svelte'",
    "(Str) payload.pull_request.head.repo.language == 'CSS'",
    "(Str) payload.pull_request.head.repo.language == 'Jupyter Notebook'",
    "(Str) payload.pull_request.head.repo.language == 'Astro'",
    "(Str) payload.pull_request.head.repo.language == 'Dockerfile'",
    "(Str) payload.pull_request.head.repo.language == 'Dart'",
    "(Str) payload.pull_request.head.repo.language == 'DM'",
    "(Str) payload.pull_request.head.repo.language == 'HCL'",
    "(Str) payload.pull_request.head.repo.language == 'SCSS'",
    "(Str) payload.pull_request.head.repo.language == 'Roff'",
    "(Str) payload.pull_request.head.repo.language == 'C'",
    "(Str) payload.pull_request.head.repo.language == 'Nix'",
    "(Str) payload.pull_request.head.repo.language == 'Kotlin'",
    "(Str) payload.pull_request.head.repo.language == 'Ruby'",
    "(Str) payload.pull_request.head.repo.language == 'Scala'",
    "(Str) payload.pull_request.head.repo.language == 'C#'",
    "(Str) payload.pull_request.head.repo.language == 'C++'",
    "(Str) payload.pull_request.head.repo.language == 'Shell'",
    "(Str) payload.pull_request.head.repo.language == 'Vue'",
    "(Str) payload.pull_request.head.repo.language == 'HTML'",
    "(Str) payload.pull_request.head.repo.language == 'Rust'",
    "(Str) payload.pull_request.head.repo.language == 'Go'",
    "(Str) payload.pull_request.head.repo.language == 'PHP'",
    "(Str) payload.pull_request.head.repo.language == 'Java'",
    "(Str) payload.pull_request.head.repo.language == 'Python'",
    "(Str) payload.pull_request.head.repo.language == 'JavaScript'",
    "(Str) payload.pull_request.head.repo.language == 'TypeScript'",
    "1"
};
