// All the file types
//
// Created by Max Norfolk on 12/12/23.


#pragma once

#include <functional>
#include <utility>

#include "psu-ds/dynarray.h"
#include "psu-ds/BitArray.h"

#include "tsl/hopscotch_map.h"

#include "jit/datatypes/types.h"
#include "core/psf.h"


namespace fishstore::plan {
    typedef uint64_t PsfAddress;
    typedef fishstore::core::PsfLookup PsfId;

    const PsfId FS_ID{};
    const PsfId NO_PSF{}; // No Psf == doing a FullScan, so they are the same value.

    struct PsfInfo {
        PsfInfo() : id(), start(0), end(0) {}

        explicit PsfInfo(PsfId id) : id(id), start(0), end(0) {}

        PsfInfo(PsfId id, PsfAddress start, PsfAddress end)
            : id(id), start(start), end(end) {}

        PsfId id;
        PsfAddress start;
        PsfAddress end;

        // returns true if a scan will contain this address
        [[nodiscard]] constexpr bool covers(const PsfAddress &addr) const { return start <= addr && end >= addr; }
    };


    // Table schema => really just a collection of attribute names, their data types, and any PSFs that map to them
    class Schema {
    public:
        struct FieldInfo {
            FieldInfo() : name(), type(ezpsf::DataType::ERROR_T), psf(NO_PSF) {}

            FieldInfo(std::string name, ezpsf::DataType type)
                : name(std::move(name)), type(type), psf(NO_PSF) {}

            FieldInfo(std::string name, ezpsf::DataType type, PsfId psf)
                : name(std::move(name)), type(type), psf(psf) {}

            [[nodiscard]] static FieldInfo StringField(std::string name_) {
                return {std::move(name_), ezpsf::DataType::STR_T};
            }

            [[nodiscard]] static FieldInfo IntField(std::string name_) {
                return {std::move(name_), ezpsf::DataType::INT32_T};
            }

            [[nodiscard]] static FieldInfo StringField(std::string name_, PsfId id) {
                assert(id.isGeneral());
                return {std::move(name_), ezpsf::DataType::STR_T, id};
            }

            [[nodiscard]] static FieldInfo IntField(std::string name_, PsfId id) {
                assert(id.isInline());
                return {std::move(name_), ezpsf::DataType::INT32_T, id};
            }

            [[nodiscard]] static FieldInfo IntField(const std::string &name_, uint32_t int_id) {
                return IntField(name_, core::PsfLookup::Inline(int_id));
            }

            [[nodiscard]] static FieldInfo StringField(const std::string &name_, uint32_t int_id) {
                return StringField(name_, core::PsfLookup::General(int_id));
            }

            friend bool operator==(const FieldInfo &lhs, const FieldInfo &rhs) {
                return lhs.name == rhs.name
                       && lhs.type == rhs.type
                       && lhs.psf == rhs.psf;
            }

            friend bool operator!=(const FieldInfo &lhs, const FieldInfo &rhs) {
                return !(lhs == rhs);
            }

            std::string name;
            fishstore::ezpsf::DataType type;
            PsfId psf;

            struct Hash {
                // generated by Clion Nova 2023.3 EAP
                std::size_t operator()(const FieldInfo &obj) const {
                    std::size_t seed = 0x27CB2BF7;
                    seed ^= (seed << 6) + (seed >> 2) + 0x275FC473 + std::hash<std::string>{}(obj.name);
                    seed ^= (seed << 6) + (seed >> 2) + 0x510C6FF4 + static_cast<std::size_t>(obj.type);
                    seed ^= (seed << 6) + (seed >> 2) + 0x6C47DA0A + PsfId::hash(obj.psf);
                    return seed;
                }
            };
        };

        Schema() : field_infos() {}

        explicit Schema(psudb::DynamicArray<FieldInfo> fields) : field_infos(std::move(fields)),
                                                                 psf_map(field_infos.size()),
                                                                 field_map(field_infos.size()) {
            for (uint32_t index = 0; index < field_infos.size(); ++index) {
                if (field_infos[index].psf != NO_PSF)
                    psf_map.emplace(field_infos[index].psf, index);

                field_map.emplace(field_infos[index].name, index);
            }
        }

        [[nodiscard]] FieldInfo at(uint32_t index) const { return field_infos[index]; }

        [[nodiscard]] uint32_t findField(const std::string &str) const { return field_map.at(str); }

        // returns the number of attributes in the schema
        [[nodiscard]] size_t size() const { return field_infos.size(); }

        static Schema merge(const Schema &s1, const Schema &s2) {
            psudb::DynamicArray<FieldInfo> ret(s1.size() + s2.size());
            int i = 0;
            for (const auto &value: s1.field_infos)
                ret[i++] = value;
            for (const auto &value: s2.field_infos)
                ret[i++] = value;
            return Schema{ret};
        }

    private:
        psudb::DynamicArray<FieldInfo> field_infos;
        tsl::hopscotch_map<PsfId, uint32_t> psf_map; // stores index in field_info of this psf
        tsl::hopscotch_map<std::string, uint32_t> field_map; // stores the index in field_info of this field name

        /////////////////////////////////////////////////////
        // Iterators
        /////////////////////////////////////////////////////

        // iterator used when looking specifically for PSF information
        // if you are not using PSF information, you do not need to use this
        class PsfIterator {
        public:
            explicit PsfIterator(const Schema *schema)
                : schema(schema), bit_map(schema->size()), arr_index(0), viewable_index(-1) {}

            // Returns true if there is a next element
            bool next() {
                // find next open slot
                while (arr_index < bit_map.size()) {
                    if (!bit_map.is_set(arr_index)) {
                        viewable_index = arr_index;
                        arr_index++;
                        return true;
                    }

                    arr_index++;
                }
                return false;
            }

            // returns true if this PSF is used
            bool next(PsfId id) {
                const auto map_it = schema->psf_map.find(id);
                if (map_it == schema->psf_map.end())
                    return false;

                // found it
                viewable_index = map_it->second;
                bit_map.set(viewable_index);
                return true;
            }

            // index into th field_infos array
            [[nodiscard]] uint32_t getCurrentIndex() const { return viewable_index; }

            const FieldInfo &operator*() const {
                return schema->field_infos[viewable_index];
            }

            const FieldInfo *operator->() const {
                return &schema->field_infos[viewable_index];
            }

        private:
            const Schema *schema;
            psudb::BitArray bit_map; // tracks what indexes have been hit
            uint32_t arr_index;
            uint32_t viewable_index;
        };

        class StandardIterator {
        public:
            explicit StandardIterator(const Schema *schema)
                : schema(schema), index(-1) {}

            bool next() {
                index++;
                return index < schema->size();
            }

            [[nodiscard]] uint32_t getCurrentIndex() const { return index; }

            const FieldInfo &operator*() const {
                return schema->field_infos.at(index);
            }

            const FieldInfo *operator->() const {
                return &schema->field_infos.at(index);
            }

        private:
            const Schema *schema;
            uint32_t index;
        };

    public:
        [[nodiscard]] StandardIterator begin() const {
            return StandardIterator{this};
        }

        [[nodiscard]] PsfIterator psf_begin() const {
            return PsfIterator{this};
        }

        [[nodiscard]] std::string toString() const {
            auto it = begin();
            std::string ret = "Schema:[";
            while (it.next()) {
                ret += "(" + it->name + ", " + getName(it->type);
                if (it->psf != NO_PSF) {
                    ret += +", " + it->psf.toString();
                }
                ret += "), ";
            }
            return ret.substr(0, ret.length() - 2) + "]";
        }
    };

    // Maps PSF id to PsfInfo
    typedef std::unordered_map<PsfId, PsfInfo> PsfMap;
}
